name: SSH
description: Execute commands on remote servers.
author: https://adabay.rocks
requirements: []
configuration:
  properties:
    server_address:
      type: string
    port:
      type: integer
    username:
      type: string
    private_key_env_variable:
      type: string
    injected_env_variables:
      type: array
    debug:
      type: boolean
  required:
    - server_address
    - username
    - private_key_env_variable
